export { default as FacebookIcon } from './facebook-icon'
export { default as EmailIcon } from './email-icon'
export { default as GithubIcon } from './github-icon'
export { default as InstagramIcon } from './instagram-icon'
export { default as LinkedinIcon } from './linkedin-icon'
export { default as TwitterIcon } from './twitter-icon'
export { default as YoutubeIcon } from './youtube-icon'
