name: Lighthouse Audit & Deploy Netlify
on: [pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Lighthouse Audit
        uses: jakejarvis/lighthouse-action@master
        with:
          netlify_site: 'gatsby-sseon-starter.netlify.com'
      - uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'
